import { z } from 'zod';

export const BuildingTypeEnumSchema = z.enum([
    "apothecary",
    "bakery",
    "bloomery",
    "boardinghouse",
    "brewery",
    "brickworks",
    "butchery",
    "carpentry",
    "cartshed",
    "cathedral",
    "center",
    "ceramic kiln",
    "chandlery",
    "chapel",
    "charcoal hut",
    "charcoal kiln",
    "church",
    "clay pit",
    "copper mine",
    "coppersmith",
    "cottage",
    "dairy",
    "dye boiler",
    "dyeworks",
    "farmstead",
    "fisher",
    "fishing shack",
    "flax farm",
    "foundry",
    "glass blower",
    "glass house",
    "gold mine",
    "grain farm",
    "guardhouse",
    "herb garden",
    "hjell",
    "household",
    "hunting lodge",
    "iron mine",
    "jeweller",
    "lead mine",
    "leatherworks",
    "logging camp",
    "markethall",
    "malthouse",
    "mansion",
    "mint",
    "net maker",
    "outpost",
    "park",
    "pasture",
    "quarry",
    "retting pit",
    "ropewalk",
    "sail loft",
    "saltery",
    "salt mine",
    "sawmill",
    "sewing shop",
    "shipyard",
    "smithy",
    "smokery",
    "spinnery",
    "stable",
    "storehouse",
    "square",
    "tannery",
    "tar kiln",
    "toolworks",
    "townhall",
    "townhouse",
    "townroad",
    "vignoble",
    "warehouse",
    "weavery",
    "windmill"
]);

export type BuildingTypeEnumType = z.infer<typeof BuildingTypeEnumSchema>;
