import { z } from 'zod';

export const RecipeEnumSchema = z.enum([
    "bake bread 1",
    "bake bread 2",
    "bake pasties 1",
    "bake pasties 2",
    "bake pies 1",
    "bind garments 1",
    "bind garments 2",
    "blow glassware 1",
    "blow glassware 2",
    "boil dye 1",
    "boil dye 2",
    "border patrol 1",
    "border patrol 2",
    "breed cattle 1a",
    "breed cattle 1b",
    "breed cattle 2a",
    "breed cattle 2b",
    "brew beer 1",
    "brew beer 2",
    "brew beer 3",
    "brew beer 4",
    "brew hop beer 1",
    "brew hop beer 2",
    "build cog 1",
    "build cog 2",
    "build handcart 1",
    "build handcart 2",
    "build hulk 1",
    "build snekkja 1",
    "build snekkja 2",
    "build tumbrel 1",
    "burn bricks 1",
    "burn charcoal 1",
    "burn charcoal 2",
    "burn charcoal 3",
    "burn charcoal 4",
    "burn cookware 1",
    "burn cookware 2",
    "burn glass 1",
    "burn lime 1",
    "burn tar 1",
    "burn tar 2",
    "burn tiles 1",
    "burn tiles 2",
    "butcher cattle 1a",
    "butcher cattle 1b",
    "butcher cattle 2",
    "carting 1",
    "carting 2",
    "churn butter 1",
    "churn butter 2",
    "cog operations",
    "craft arms 1",
    "craft belts 1",
    "craft belts 2",
    "craft belts 3",
    "craft belts 4",
    "craft cookware 1",
    "craft furniture 1",
    "craft furniture 2",
    "craft furniture 3",
    "craft furniture 4",
    "craft ploughs 1",
    "craft ploughs 2",
    "craft ploughs 3",
    "craft scythes 1",
    "craft scythes 2",
    "craft tools 1",
    "craft tools 2",
    "craft wheels 1",
    "craft wheels 2",
    "craft wheels 3",
    "cut bricks 1",
    "cut grindstones 1",
    "delivery duty 1",
    "delivery duty 2",
    "dig clay 1",
    "dig clay 2",
    "distill spirits 1",
    "distill spirits 2",
    "dry fish 1",
    "dry fish 2",
    "dry stockfish 1",
    "dry stockfish 2",
    "dye cloth 1",
    "dye cloth 2",
    "extract stone 1",
    "extract stone 2",
    "extract stone 3",
    "fishing 1",
    "fishing 2a",
    "fishing 2b",
    "fishing 3",
    "forge arms 1",
    "forge arms 2",
    "forge arms 2b",
    "forge axes 1",
    "forge axes 1b",
    "forge axes 2",
    "forge axes 2b",
    "forge blades 1",
    "forge blades 1b",
    "forge blades 2",
    "forge blades 2b",
    "forge mouldboards 1",
    "forge pickaxes 1",
    "forge pickaxes 1b",
    "forge pickaxes 2",
    "forge pickaxes 2b",
    "forge swords 1",
    "forge swords 1b",
    "forge swords 2",
    "forge swords 2b",
    "forge tools 1",
    "forge tools 2",
    "forge tools 3",
    "gather firewood 1",
    "gather firewood 2",
    "gather resin 1",
    "gather resin 2",
    "grain payment",
    "grow flax 1",
    "grow flax 2",
    "grow flax 3",
    "grow flax 4a",
    "grow flax 4b",
    "grow grain 1",
    "grow grain 2",
    "grow grain 3a",
    "grow grain 3b",
    "grow grain 4a",
    "grow grain 4b",
    "grow herbs 1",
    "grow herbs 2",
    "hammer nails 1",
    "handcart operations",
    "harness ox 1",
    "harness ox 2a",
    "harness ox 2b",
    "harness ox 3a",
    "harness ox 3b",
    "harness ox 4a",
    "harness ox 4b",
    "herd sheep 1",
    "herd sheep 2",
    "hold banquet 1a",
    "hold banquet 1b",
    "hold banquet 2a",
    "hold banquet 2b",
    "hold banquet 2c",
    "hold banquet 3a",
    "hold banquet 3b",
    "hold banquet 3c",
    "hold banquet 4a",
    "hold banquet 4b",
    "hold feast 1",
    "hold feast 2",
    "hold feast 3",
    "hold mass 1",
    "hold mass 2",
    "hold mass 3",
    "hold prayer 1",
    "hold prayer 2",
    "hold prayer 3",
    "hold sermon 1",
    "hold sermon 2a",
    "hold sermon 2b",
    "hold sermon 3a",
    "hold sermon 3b",
    "hulk operations",
    "hunting 1",
    "hunting 2",
    "hunting 3",
    "hunting 4",
    "hunting 5",
    "keep bees 1",
    "knight duty 1",
    "knight duty 2",
    "knight duty 3",
    "knight duty 4",
    "knit garments 1",
    "knit garments 2",
    "let cottages 1",
    "let cottages 2",
    "logging 1",
    "logging 2",
    "logging 3",
    "maintain 1",
    "make alembics 1",
    "make alembics 2",
    "make bricks 1",
    "make bricks 2",
    "make candles 1",
    "make candles 2",
    "make casks 1",
    "make casks 2",
    "make cheese 1",
    "make cheese 2",
    "make cheese 3",
    "make cheese 4",
    "make cheese 5",
    "make harnesses 1",
    "make harnesses 2",
    "make harnesses 2b",
    "make jewellery 1",
    "make jewellery 2",
    "make leather armor 1",
    "make medicine 1",
    "make medicine 2",
    "make nets 1",
    "make nets 2",
    "make nets 3",
    "make rope 1",
    "make windows 1",
    "make wine 1",
    "make wine 2",
    "make wine 3",
    "malting 1",
    "malting 2",
    "milling 1",
    "milling 2",
    "milling 3",
    "mine copper 1",
    "mine copper 2",
    "mine copper 3",
    "mine copper 4",
    "mine copper 5",
    "mine gold 1",
    "mine gold 1b",
    "mine gold 2",
    "mine gold 2b",
    "mine gold 3",
    "mine iron 1",
    "mine iron 2",
    "mine iron 3",
    "mine iron 4",
    "mine iron 5",
    "mine lead 1",
    "mine lead 2",
    "mine lead 2b",
    "mine lead 3",
    "mine lead 3b",
    "mine lead 4",
    "mine salt 1",
    "mine salt 2",
    "mine salt 3",
    "mint copper coins 1",
    "mint copper coins 2",
    "mint copper coins 3",
    "mint gold coins 1",
    "mint gold coins 2",
    "mint gold coins 3",
    "mint leather coins 1",
    "mint silver coins 1",
    "mint silver coins 2",
    "mint silver coins 3",
    "mint steel coins 1",
    "patrol 1",
    "patrol 2a",
    "patrol 2b",
    "patrol 3a",
    "patrol 3b",
    "refine steel 1",
    "refine steel 1b",
    "refine steel 2",
    "refine steel 2b",
    "retting 1",
    "retting 2",
    "salting fish 1",
    "salting fish 2",
    "salting meat 1",
    "salting meat 2",
    "sawing 1",
    "sawing 2",
    "sawing 3",
    "sawing 4",
    "service 1",
    "service 2",
    "service 3",
    "service 4",
    "sew coats 1a",
    "sew coats 1b",
    "sew coats 2a",
    "sew coats 2b",
    "sew gambeson 1",
    "sew garments 1",
    "sew garments 2a",
    "sew garments 2b",
    "sew garments 3a",
    "sew garments 3b",
    "sew garments 4a",
    "sew garments 4b",
    "sew sails 1",
    "sew sails 2",
    "shear sheep 1",
    "shear sheep 2",
    "shear sheep 3",
    "smelt copper 1",
    "smelt copper 2",
    "smelt gold 1",
    "smelt gold 2",
    "smelt iron 1",
    "smelt iron 2",
    "smelt lead 1",
    "smelt lead 2a",
    "smelt lead 2b",
    "smelt lead 3 (silver)",
    "smoking fish 1",
    "smoking fish 2",
    "smoking ham 1",
    "smoking ham 2",
    "smoking meat 1",
    "smoking meat 2",
    "snekkja operations",
    "spin thread 1",
    "spin thread 2",
    "spin yarn 1",
    "spin yarn 2",
    "split timber 1",
    "split timber 2",
    "tan hides 1",
    "tan hides 2",
    "trap fish 1",
    "trap fish 2",
    "trap fish 3",
    "trapping 1",
    "trapping 2",
    "tumbrel operations",
    "weave cloth 1",
    "weave cloth 2a",
    "weave cloth 2b",
    "weave cloth 3a",
    "weave cloth 3b",
    "weave cloth 4a",
    "weave cloth 4b",
    "yoke ox 1a",
    "yoke ox 1b",
    "yoke ox 2a",
    "yoke ox 2b",
    "yoke ox 3",
    "yoke ox 3 (manure)"
]);

export type RecipeEnum = z.infer<typeof RecipeEnumSchema>;
